name: spotme
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
module:
  androidX: true
dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.2
  # firebase packages
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  # provides user updates to the app at all times
  provider: ^5.0.0
  # provides fancy percentage indicators
  percent_indicator: ^3.0.1
  # provides fancy spinning animations
  flutter_spinkit: ^5.0.0
  # used to generate unique ids
  uuid: ^3.0.4
  intl: ^0.17.0
  # used to acquire fonts
  google_fonts: ^2.1.0
  spring_button: ^2.0.0
  flutter_typeahead: ^4.1.1

  # used for re-orderable list
  reorderables: ^0.4.1
  implicitly_animated_reorderable_list: ^0.4.1
  firebase_ui_auth: ^1.0.4
  modal_bottom_sheet: ^2.1.2
  animations: ^2.0.7
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  image_path: "resources/images/icon/dumbell.png"
  adaptive_icon_foreground: "resources/images/icon/dumbell.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  ios: true
  image_path_ios: "resources/images/icon/ios.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - resources/images/work_in_progress/wip.png
    - resources/images/icon/dumbell.png
    - "resources/images/icon/ios.png"
    - resources/images/visuals/undraw_working_out_re_nhkg.svg
    - resources/images/visuals/undraw_personal_trainer_2.svg
  fonts:
    - family: Red Hat Text
      fonts:
        - asset: resources/fonts/RedHatText-Medium.ttf
